<?php

namespace Symsite\Bundle\BlogBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function qbFindWithCategoryBy()
    {
        return $this->createQueryBuilder('a')
          ->select('a', 'c')
          ->leftJoin('a.category', 'c');
    }

    /**
     * @param array $ids
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function qbDeleteByIds(array $ids)
    {
        return $this->createQueryBuilder('a')
          ->delete()
          ->where('a.id IN(:ids)')
          ->setParameter('ids', $ids);
    }
}
