<?php

namespace Symsite\Bundle\UploadFileBundle\Entity;

/**
 * UploadFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadFileRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function qbFindByIds(array $ids)
    {
        return $this->createQueryBuilder('u')
          ->where('u.id IN(:ids)')
          ->setParameter('ids', $ids);
    }
}
